language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

before_script: '[ "$TRAVIS_PHP_VERSION" != "7.3" ] && composer update'
script: make test

cache:
  directories:
    - $HOME/.composer/cache/files
